#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 27 13:41:57 2020

@author: thausmann
"""
import numpy as np


def matrix_solve(left, right):
    left, right = np.array(left, 'float64'), np.array(right, 'float64')
    for i,row in enumerate(left):
        right[i] *= 1 / row[i] 
        row *= 1 / row[i] 
        for below in left[i+1:]:
            right[i+1] -= right[i] * below[i]
            below -= row * below[i]
    solution = np.zeros(len(right))
    for i, row in [(a, b) for a, b in enumerate(left)][::-1]:
        right[i] -= np.dot(row, solution)
        solution[i] = right[i]
    return solution
            